### ISSUE TITLE
按 opensgp 规范，如何在 schema中描述 entityType  与其他 entityType 对象一对多的映射关系

### ISSUE THREAD

**Issue by zhuzhaoyun** [OpenSPG/KAG#126]
### Search before asking

- [X] I had searched in the [issues](https://github.com/OpenSPG/KAG/issues?q=is%3Aissue) and found no similar issues.

### Operating system information

Linux

### What happened

我尝试用 entityType 对象的数组属性来schema 的创建，报错不符合语法规范。
* 报错提示 schema 
    elements(包含元素): [Element]
      desc: 本空间内包含的元素
      constraint: [CableProtectionPipe,SpecialLightingCable]
* 命令执行错误如下
knext schema commit
Traceback (most recent call last):
  File "/home/zzy/miniconda3/envs/kag-demo/bin/knext", line 8, in <module>
    sys.exit(_main())
  File "/home/zzy/miniconda3/envs/kag-demo/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/zzy/miniconda3/envs/kag-demo/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/zzy/miniconda3/envs/kag-demo/lib/python3.10/site-packages/knext/command/exception.py", line 21, in invoke
    return super().invoke(ctx)
  File "/home/zzy/miniconda3/envs/kag-demo/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zzy/miniconda3/envs/kag-demo/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zzy/miniconda3/envs/kag-demo/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zzy/miniconda3/envs/kag-demo/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/zzy/miniconda3/envs/kag-demo/lib/python3.10/site-packages/knext/command/sub_command/schema.py", line 38, in commit_schema
    ml = SPGSchemaMarkLang(schema_file)
  File "/home/zzy/miniconda3/envs/kag-demo/lib/python3.10/site-packages/knext/schema/marklang/schema_ml.py", line 172, in __init__
    self.load_script()
  File "/home/zzy/miniconda3/envs/kag-demo/lib/python3.10/site-packages/knext/schema/marklang/schema_ml.py", line 1079, in load_script
    self.parsing_dispatch(strip_line, self.current_parsing_level)
  File "/home/zzy/miniconda3/envs/kag-demo/lib/python3.10/site-packages/knext/schema/marklang/schema_ml.py", line 877, in parsing_dispatch
    self.parse_predicate(expression)
  File "/home/zzy/miniconda3/envs/kag-demo/lib/python3.10/site-packages/knext/schema/marklang/schema_ml.py", line 582, in parse_predicate
    assert match, self.error_msg(
AssertionError: Line# 52: Unrecognized expression, expect pattern like english(Chinese):Type (Please refer https://spg.openkg.cn/tutorial/schema/dsl for details)

### How to reproduce

完整 schema 文件如下：

namespace KagDemo

##================================Element======================================
Element(元素): EntityType
  desc: 构成建筑结构的具体组件，如灯光电缆、机位牌等。
  properties:
    elementName(元素名称): Text
      desc: 元素的名称。
      constraint: NotNull

# 定义具体的元素子类
CableProtectionPipe(电缆保护管) -> Element:
  desc: 用于保护电缆的管道。
  properties:
    diameter(直径): Float
      desc: 保护管的直径，单位为毫米。
      constraint: Positive

SpecialLightingCable(灯光专用电缆) -> Element:
  desc: 专门用于照明系统的电缆。
  properties:
    voltageRating(额定电压): Float
      desc: 电缆的额定电压，单位为伏特。
      constraint: Positive

#==============================Space===========================================
Space(空间): EntityType
  desc: 工程建筑项目中的具体空间区域，如楼栋、楼层、跑道等。
  properties:
    spaceName(空间名称): Text
      desc: 空间的名称。
      constraint: NotNull

# 定义实体类型 - 跑道 (Runway)，继承自 Space
Runway(跑道) -> Space:
  desc: 机场中用于飞机起降的具体空间区域。
  properties:
    length(长度): Float
      desc: 跑道的总长度，单位为米。
      constraint: Positive
    width(宽度): Float
      desc: 跑道的宽度，单位为米。
      constraint: Positive
    elements(包含元素): [Element]
      desc: 本空间内包含的元素
      constraint: [CableProtectionPipe,SpecialLightingCable]

我的目的是想要实现表达  
Runway 这个空间对象中包含了以下两个 CableProtectionPipe、SpecialLightingCable，甚至多个元素

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by matthewhyx** [comment]
您好，根据您贴的信息，发现有几项问题需要确认：
1. Schema声明需要严格缩进，请确保文件里是按说明严格缩进。
2. 部分contraint的值域不太正确，目前没有Positive, [xxx, xx]这样的表达。
3. 报错信息最后一行有提示错误: Line# 52: Unrecognized expression, expect pattern like english(Chinese):Type，可以对照这个提示检查Schema文件内容

可详细参考Schema说明：https://openspg.yuque.com/ndx6g9/nmwkzz/lkxg1clqkei1l69v

**Comment by RiceCake1106** [comment]
我这里其他的都可以简化掉，但有个最主要的问题是，因为这里不支持数组的表述，我如何在 schema 中表述空间 A 中包含 B、C 对象？ 即如何表达 Runway 对象中如何包含了 CableProtectionPipe、SpecialLightingCable，这个是使我困惑的地方

namespace KagDemo

##================================Element======================================
Element(元素): EntityType
    desc: 构成建筑结构的具体组件，如灯光电缆、机位牌等。
    properties:
        elementName(元素名称): Text
            desc: 元素的名称。
            constraint: NotNull

# 定义具体的元素子类
CableProtectionPipe(电缆保护管) -> Element:
    desc: 用于保护电缆的管道。
    properties:
        diameter(直径): Float
            desc: 保护管的直径，单位为毫米。
            constraint: NotNull

SpecialLightingCable(灯光专用电缆) -> Element:
    desc: 专门用于照明系统的电缆。
    properties:
        voltageRating(额定电压): Float
            desc: 电缆的额定电压，单位为伏特。
            constraint: NotNull

#==============================Space===========================================
Space(空间): EntityType
    desc: 工程建筑项目中的具体空间区域，如楼栋、楼层、跑道等。
    properties:
        spaceName(空间名称): Text
            desc: 空间的名称。
            constraint: NotNull

# 定义实体类型 - 跑道 (Runway)，继承自 Space
Runway(跑道) -> Space:
    desc: 机场中用于飞机起降的具体空间区域。
    properties:
        elements(包含元素): Element
            desc: 本空间内包含的元素。
            constraint:  Enum=[CableProtectionPipe, SpecialLightingCable]

**Comment by RiceCake1106** [comment]
我这里其他的都可以简化掉，但有个最主要的问题是，因为这里不支持数组的表述，我如何在 schema 中表述空间 A 中包含 B、C 对象？ 即如何表达 Runway 对象中如何包含了 CableProtectionPipe、SpecialLightingCable，这个是使我困惑的地方，使用文档中的 枚举等也不行

namespace KagDemo
===============================Element======================================
Element(元素): EntityType
    desc: 构成建筑结构的具体组件，如灯光电缆、机位牌等。
    properties:
        elementName(元素名称): Text
            desc: 元素的名称。
            constraint: NotNull

定义具体的元素子类
CableProtectionPipe(电缆保护管) -> Element:
    desc: 用于保护电缆的管道。
    properties:
        diameter(直径): Float
            desc: 保护管的直径，单位为毫米。
            constraint: NotNull

SpecialLightingCable(灯光专用电缆) -> Element:
    desc: 专门用于照明系统的电缆。
    properties:
        voltageRating(额定电压): Float
            desc: 电缆的额定电压，单位为伏特。
            constraint: NotNull

=====================Space===========================================
Space(空间): EntityType
    desc: 工程建筑项目中的具体空间区域，如楼栋、楼层、跑道等。
    properties:
        spaceName(空间名称): Text
            desc: 空间的名称。
            constraint: NotNull

定义实体类型 - 跑道 (Runway)，继承自 Space
Runway(跑道) -> Space:
    desc: 机场中用于飞机起降的具体空间区域。
    properties:
        elements(包含元素): Element
            desc: 本空间内包含的元素。
            constraint:  Enum=[CableProtectionPipe, SpecialLightingCable]

**Comment by RiceCake1106** [comment]
我这里的主要问题是  Runway 这个 schema 对象的描述中，该用什么用的方式来表达 Runway 空间中包含了  CableProtectionPipe、CableProtectionPipe 元素，期望能给出示例

**Comment by RiceCake1106** [comment]
![Uploading a4bc8dcd07cfcbc3148c99d05ccff81.png…]()
这种关联方法也不行

**Comment by matthewhyx** [comment]
您好，根据您的反馈，

> 我这里的主要问题是 Runway 这个 schema 对象的描述中，该用什么用的方式来表达 Runway 空间中包含了 CableProtectionPipe、CableProtectionPipe 元素，期望能给出示例

是否是指Runway有contains关系指向CableProtectionPipe/SpecialLightingCable？如果是的话，需要先定义CableProtectionPipe 和 SpecialLightingCable 实体类型，再在Runway的关系定义中增加两条contains关系，分别指向CableProtectionPipe 和 SpecialLightingCable。

```yaml
CableProtectionPipe(电缆保护管): EntityType

SpecialLightingCable(专用照明电缆): EntityType

Runway(跑道) -> Space:
    relations:
        contains(包含): CableProtectionPipe
        contains(包含): SpecialLightingCable
```
