### ISSUE TITLE
问答嵌入错误

### ISSUE THREAD

**Issue by mars216** [OpenSPG/KAG#13]
我在创建了源代码系统自带的KagDemo之后，然后再上传文件进行创建任务，但是出现向量生成
2024-10-31 10:56:06: Start vectorizer processor...
2024-10-31 10:56:06: invoke vectorizer processor operator:BatchVectorizer
2024-10-31 10:56:08: execute error:java.util.concurrent.ExecutionException: pemja.core.PythonException: <class 'openai.APIConnectionError'>: Connection error.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at 
我的配置文档如下，其中我将ollama部署在docker里面在
[vectorizer]
vectorizer = kag.common.vectorizer.OpenAIVectorizer
model = bge_m3
api_key = EMPTY
base_url = http://127.0.0.1:11434/v1
vector_dimensions = 1024

[llm]
client_type = maas
base_url = https://api.deepseek.com

**Comment by xionghuaidong** [comment]
我将ollama部署在docker里面 -- 这是因为 release-openspg-server 访问您 ollama 容器的网络链路不通。请将 http://127.0.0.1:11434/v1 换成可以 ping 通的 IP 地址。

或者您也可以先试试内置的 BAAI/bge-base-zh-v1.5 模型，参考 [使用内置向量化模型](https://openspg.yuque.com/ndx6g9/0.5/yofw66sq5ncerf4i)。
```text
[vectorizer]
vectorizer = kag.common.vectorizer.LocalBGEVectorizer
path = ~/.cache/vectorizer/BAAI/bge-base-zh-v1.5
vector_dimensions = 768
```
