### ISSUE TITLE
Example TwoWiki (2Wiki) and HotPotQA don't work

### ISSUE THREAD

**Issue by damianoct** [OpenSPG/KAG#194]
### Search before asking

- [X] I had searched in the [issues](https://github.com/OpenSPG/KAG/issues?q=is%3Aissue) and found no similar issues.

### Operating system information

MacOS(x86)

### What happened

I was tried to execute two examples following the guide TwoWiki (https://openspg.yuque.com/ndx6g9/wc9oyq/sxo9qz1m9wbnsqxz) and HotPotQA (https://openspg.yuque.com/ndx6g9/wc9oyq/acyweykbfyoqy6ad).

My setup include OpenAI as LLM and a vector size of 1536 (the 1024 size is wrong because during the evaluation it fails)

For two wiki example I encountered the following problems:

- During the Knowledge Import Task there was en error during the process:
```bash
Traceback (most recent call last):
  File "/Users/a469083/personal/kag/KAG/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
  File "/Users/a469083/personal/kag/KAG/kag/builder/component/extractor/kag_extractor.py", line 95, in named_entity_recognition
    return kg_result + ner_result
TypeError: can only concatenate list (not "dict") to list
```
- During the eval
```bash
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "/Users/a469083/personal/kag/KAG/kag/examples/2wiki/solver/evaFor2wiki.py", line 49, in process_sample
    prediction, traceLog = self.qa(question)
  File "/Users/a469083/personal/kag/KAG/kag/examples/2wiki/solver/evaFor2wiki.py", line 31, in qa
    answer, traceLog = resp.run(query)
  File "/Users/a469083/personal/kag/KAG/kag/solver/logic/solver_pipeline.py", line 54, in run
    solved_answer, supporting_fact, history_log = self.reasoner.reason(present_instruction)
  File "/Users/a469083/personal/kag/KAG/kag/solver/implementation/default_reasoner.py", line 66, in reason
    solved_answer, sub_qa_pair, recall_docs, history_qa_log = self.lf_solver.solve(question, lf_nodes)
  File "/Users/a469083/personal/kag/KAG/kag/solver/logic/core_modules/lf_solver.py", line 161, in solve
    cur_step_recall_docs = self.chunk_retriever.recall_docs(query)
  File "/Users/a469083/personal/kag/KAG/kag/solver/implementation/lf_chunk_retriever.py", line 50, in recall_docs
    return super().recall_docs(query, top_k, **kwargs)
  File "/Users/a469083/personal/kag/KAG/kag/common/retriever/kag_retriever.py", line 325, in recall_docs
    self.append_official_name(ner_list, std_ner_list)
  File "/Users/a469083/personal/kag/KAG/kag/common/retriever/kag_retriever.py", line 140, in append_official_name
    name = tmp_entity["entity"]
TypeError: string indices must be integers
```

I see from neo4j browser that some relationship were created so I tried to ask a question through the UI, but this is the result:

<img width="911" alt="image" src="https://github.com/user-attachments/assets/bd7a1579-0356-4d0b-b276-6e4984aeb2e0" />

### How to reproduce

1. run the docker compose command to deploy server + neo4j + mysql
2. restore the project as stated in the doc (https://openspg.yuque.com/ndx6g9/wc9oyq/sxo9qz1m9wbnsqxz)
3. change the vector size of the project to 1536
4. build and evalaute the KB
5. try to answer a question

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by nileshmalode11** [comment]
"I am also facing the same issue with KAG v0.6. Specifically, I encountered the following error:
TypeError: string indices must be integers in the std.py file during entity processing, indicating that the response structure is not as expected. Despite following the updated documentation and adjusting the configuration (e.g., vector size to 1536), the issue persists during retrieval and evaluation.

It seems the entity handling or response parsing in the pipeline is encountering malformed data. Can you confirm if there are additional steps or fixes required for KAG v0.6? Any guidance would be greatly appreciated."

**Comment by caszkgui** [comment]
> "I am also facing the same issue with KAG v0.6. Specifically, I encountered the following error: TypeError: string indices must be integers in the std.py file during entity processing, indicating that the response structure is not as expected. Despite following the updated documentation and adjusting the configuration (e.g., vector size to 1536), the issue persists during retrieval and evaluation.
> 
> It seems the entity handling or response parsing in the pipeline is encountering malformed data. Can you confirm if there are additional steps or fixes required for KAG v0.6? Any guidance would be greatly appreciated."

LLM may return a non-standard JSON format with a certain probability, which may cause parsing errors. You can rerun the program a few times to resolve the error. Successful cases will be written into ckpt and will be skipped during the rerun phase.

**Comment by caszkgui** [comment]
> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/OpenSPG/KAG/issues?q=is%3Aissue) and found no similar issues.
> 
> ### Operating system information
> MacOS(x86)
> 
> ### What happened
> I was tried to execute two examples following the guide TwoWiki (https://openspg.yuque.com/ndx6g9/wc9oyq/sxo9qz1m9wbnsqxz) and HotPotQA (https://openspg.yuque.com/ndx6g9/wc9oyq/acyweykbfyoqy6ad).
> 
> My setup include OpenAI as LLM and a vector size of 1536 (the 1024 size is wrong because during the evaluation it fails)
> 
> For two wiki example I encountered the following problems:
> 
> * During the Knowledge Import Task there was en error during the process:
> 
> Traceback (most recent call last):
>   File "/Users/a469083/personal/kag/KAG/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 478, in __call__
>     result = fn(*args, **kwargs)
>   File "/Users/a469083/personal/kag/KAG/kag/builder/component/extractor/kag_extractor.py", line 95, in named_entity_recognition
>     return kg_result + ner_result
> TypeError: can only concatenate list (not "dict") to list
> * During the eval
> 
> INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
> Traceback (most recent call last):
>   File "/Users/a469083/personal/kag/KAG/kag/examples/2wiki/solver/evaFor2wiki.py", line 49, in process_sample
>     prediction, traceLog = self.qa(question)
>   File "/Users/a469083/personal/kag/KAG/kag/examples/2wiki/solver/evaFor2wiki.py", line 31, in qa
>     answer, traceLog = resp.run(query)
>   File "/Users/a469083/personal/kag/KAG/kag/solver/logic/solver_pipeline.py", line 54, in run
>     solved_answer, supporting_fact, history_log = self.reasoner.reason(present_instruction)
>   File "/Users/a469083/personal/kag/KAG/kag/solver/implementation/default_reasoner.py", line 66, in reason
>     solved_answer, sub_qa_pair, recall_docs, history_qa_log = self.lf_solver.solve(question, lf_nodes)
>   File "/Users/a469083/personal/kag/KAG/kag/solver/logic/core_modules/lf_solver.py", line 161, in solve
>     cur_step_recall_docs = self.chunk_retriever.recall_docs(query)
>   File "/Users/a469083/personal/kag/KAG/kag/solver/implementation/lf_chunk_retriever.py", line 50, in recall_docs
>     return super().recall_docs(query, top_k, **kwargs)
>   File "/Users/a469083/personal/kag/KAG/kag/common/retriever/kag_retriever.py", line 325, in recall_docs
>     self.append_official_name(ner_list, std_ner_list)
>   File "/Users/a469083/personal/kag/KAG/kag/common/retriever/kag_retriever.py", line 140, in append_official_name
>     name = tmp_entity["entity"]
> TypeError: string indices must be integers
> I see from neo4j browser that some relationship were created so I tried to ask a question through the UI, but this is the result:
> 
> <img alt="image" width="911" src="https://private-user-images.githubusercontent.com/1521164/399509098-bd7a1579-0356-4d0b-b276-6e4984aeb2e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ5NjQ4OTAsIm5iZiI6MTc0NDk2NDU5MCwicGF0aCI6Ii8xNTIxMTY0LzM5OTUwOTA5OC1iZDdhMTU3OS0wMzU2LTRkMGItYjI3Ni02ZTQ5ODRhZWIyZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDQxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA0MThUMDgyMzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2MzNWRjNTFlYjYyNDE0Y2Y2YmM0NWVkYWRlZTM1NGY2ZTgwMDQxMzE2NDU4ZGZmYWM2MjcyMGIyYmUyYzkxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bC13gYWSy7oa1Z90MsO5yg9uJwdiA5FcFq_yUbSCshM">
> ### How to reproduce
> 1. run the docker compose command to deploy server + neo4j + mysql
> 2. restore the project as stated in the doc (https://openspg.yuque.com/ndx6g9/wc9oyq/sxo9qz1m9wbnsqxz)
> 3. change the vector size of the project to 1536
> 4. build and evalaute the KB
> 5. try to answer a question
> 
> ### Are you willing to submit PR?
> * [ ]  Yes I am willing to submit a PR!

LLM may return a non-standard JSON format with a certain probability, which may cause parsing errors. You can rerun the program a few times to resolve the error. Successful cases will be written into ckpt and will be skipped during the rerun phase.
