### ISSUE TITLE
查询报错

### ISSUE THREAD

**Issue by kedaya0214** [OpenSPG/KAG#28]
我使用产品模式传入手册中的示例文档，图存储也成功了，但提问时出现报错
执行失败pemja.core.PythonException: <class 'AttributeError'>: 'NoneType' object has no attribute 'get'
	at /openspg_venv/lib/python3.8/site-packages/kag/solver/main_solver.invoke(main_solver.py:31)
	at /openspg_venv/lib/python3.8/site-packages/kag/solver/implementation/default_lf_planner.__init__(default_lf_planner.py:20)
	at /openspg_venv/lib/python3.8/site-packages/kag/interface/solver/lf_planner_abc.__init__(lf_planner_abc.py:15)
	at /openspg_venv/lib/python3.8/site-packages/kag/solver/common/base.__init__(base.py:114)
	at pemja.core.PythonInterpreter.invokeMethod(Native Method)
	at pemja.core.PythonInterpreter.invokeMethod(PythonInterpreter.java:118)
	at com.antgroup.openspgapp.core.reasoner.service.impl.TaskRunner$NlQueryTask.call(TaskRunner.java:143)
	at com.antgroup.openspgapp.core.reasoner.service.impl.TaskRunner$NlQueryTask.call(TaskRunner.java:122)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by xionghuaidong** [comment]
I encountered the same problem. Could you share your solution to the problem?

**Comment by xionghuaidong** [comment]
> I encountered the same problem. Could you share your solution to the problem?

Problem solved. We need to config the Prompt.

[Product](https://openspg.yuque.com/ndx6g9/wc9oyq/rgd8ecefccwd1ga5)
![image](https://github.com/user-attachments/assets/aad7f49d-7f90-4d41-87e3-e9f3c2d25acd)

[产品使用](https://openspg.yuque.com/ndx6g9/0.5/bv9zc3gyi98k0oyx)
![image](https://github.com/user-attachments/assets/a86a6c3e-ba8d-4500-81d9-58dd57a4877f)
