### ISSUE TITLE
openai.InternalServerError: Error code: 502

### ISSUE THREAD

**Issue by zxy66688** [OpenSPG/KAG#38]
Traceback (most recent call last):
  File "F:\openspg\KAG\kag\examples\musique\builder\indexer.py", line 89, in <module>
    buildKB(corpusFilePath)
  File "F:\openspg\KAG\kag\examples\musique\builder\indexer.py", line 77, in buildKB
    MusiqueBuilderChain().invoke(file_path=corpusFilePath, max_workers=20)
  File "D:\anaconda3\envs\kag-demo\lib\site-packages\knext\builder\builder_chain_abc.py", line 26, in invoke
    chain.invoke(input=file_path, max_workers=max_workers, **kwargs)
  File "D:\anaconda3\envs\kag-demo\lib\site-packages\knext\common\base\chain.py", line 64, in invoke
    node, result = future.result()
  File "D:\anaconda3\envs\kag-demo\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "D:\anaconda3\envs\kag-demo\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "D:\anaconda3\envs\kag-demo\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\anaconda3\envs\kag-demo\lib\site-packages\knext\common\base\chain.py", line 46, in execute_node
    ret = inner_future.result()
  File "D:\anaconda3\envs\kag-demo\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "D:\anaconda3\envs\kag-demo\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "D:\anaconda3\envs\kag-demo\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "f:\openspg\kag\kag\builder\component\vectorizer\batch_vectorizer.py", line 199, in invoke
    modified_input = self._generate_embedding_vectors(self.vectorizer, input)
  File "f:\openspg\kag\kag\builder\component\vectorizer\batch_vectorizer.py", line 188, in _generate_embedding_vectors
    generator.batch_generate(node_batch)
  File "f:\openspg\kag\kag\builder\component\vectorizer\batch_vectorizer.py", line 125, in batch_generate
    manager.batch_generate(self._vectorizer)
  File "f:\openspg\kag\kag\builder\component\vectorizer\batch_vectorizer.py", line 94, in batch_generate
    vectors = self._generate_vectors(vectorizer, text_batch)
  File "f:\openspg\kag\kag\builder\component\vectorizer\batch_vectorizer.py", line 84, in _generate_vectors
    vectors = vectorizer.vectorize(texts)
  File "f:\openspg\kag\kag\common\vectorizer\openai_vectorizer.py", line 57, in vectorize
    results = self.client.embeddings.create(input=texts, model=self.model)
  File "D:\anaconda3\envs\kag-demo\lib\site-packages\openai\resources\embeddings.py", line 124, in create
    return self._post(
  File "D:\anaconda3\envs\kag-demo\lib\site-packages\openai\_base_client.py", line 1278, in post
  File "D:\anaconda3\envs\kag-demo\lib\site-packages\openai\_base_client.py", line 955, in request
    return self._request(
  File "D:\anaconda3\envs\kag-demo\lib\site-packages\openai\_base_client.py", line 1044, in _request
    return self._retry_request(
  File "D:\anaconda3\envs\kag-demo\lib\site-packages\openai\_base_client.py", line 1093, in _retry_request
    return self._request(
  File "D:\anaconda3\envs\kag-demo\lib\site-packages\openai\_base_client.py", line 1044, in _request
    return self._retry_request(
  File "D:\anaconda3\envs\kag-demo\lib\site-packages\openai\_base_client.py", line 1093, in _retry_request
    return self._request(
  File "D:\anaconda3\envs\kag-demo\lib\site-packages\openai\_base_client.py", line 1059, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Error code: 502

**Comment by xionghuaidong** [comment]
Please show you vectorizer config.

**Comment by xionghuaidong** [comment]
> > Please show you vectorizer config.
> 
> vectorizer = kag.common.vectorizer.openAIVectorizer

The full content of the ``[vectorizer]`` section in kag_config.cfg please.

**Comment by zxy66688** [comment]
> > > Please show you vectorizer config.
> > 
> > 
> > vectorizer = kag.common.vectorizer.openAIVectorizer
> 
> The full content of the `[vectorizer]` section in kag_config.cfg please.

[vectorizer]
vectorizer = kag.common.vectorizer.OpenAIVectorizer
model = bge-m3
api_key = EMPTY
base_url = http://127.0.0.1:11434/v1
vector_dimensions = 1024

**Comment by zxy66688** [comment]
> > [vectorizer] vectorizer = kag.common.vectorizer.OpenAIVectorizer
> > model = bge-m3
> > api_key = EMPTY
> > base_url = http://127.0.0.1:11434/v1
> > vector_dimensions = 1024
> 
> The ip address in `base_url` might be incorrect. You may need to change `base_url` to `http://host.docker.internal:11434/v1`. Please refere to [5. Configure KAG to use the bge-m3 model deployed with Ollama](https://openspg.yuque.com/ndx6g9/wc9oyq/agc1runp50cz3wu8#S5mzB).
> 
> ![image](https://private-user-images.githubusercontent.com/5087599/384463166-fea5f3cb-f062-4916-9aed-3811ed6ffe96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzE5NDgsIm5iZiI6MTczMTEzMTY0OCwicGF0aCI6Ii81MDg3NTk5LzM4NDQ2MzE2Ni1mZWE1ZjNjYi1mMDYyLTQ5MTYtOWFlZC0zODExZWQ2ZmZlOTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDlUMDU1NDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDc3ZjljYzY4NGMzZjRiZjQwOWUzMjNhMTE3ZDY2ZmQxOWI0MTc1MTA2Y2QwNjdhNGEzZTgzMTc1NTc2NTZlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AGM13y2sPbBzgi1cudI6IkcqPf3PbL5lmDR7xzMUHb4)

i have changed the base_url,but still have the same problem
[vectorizer]
vectorizer = kag.common.vectorizer.OpenAIVectorizer
model = bge-m3
api_key = EMPTY
base_url = http://host.docker.internal:11434/v1
vector_dimensions = 1024

**Comment by caszkgui** [comment]
> > > [vectorizer] vectorizer = kag.common.vectorizer.OpenAIVectorizer
> > > model = bge-m3
> > > api_key = EMPTY
> > > base_url = http://127.0.0.1:11434/v1
> > > vector_dimensions = 1024
> > 
> > 
> > The ip address in `base_url` might be incorrect. You may need to change `base_url` to `http://host.docker.internal:11434/v1`. Please refere to [5. Configure KAG to use the bge-m3 model deployed with Ollama](https://openspg.yuque.com/ndx6g9/wc9oyq/agc1runp50cz3wu8#S5mzB).
> > ![image](https://private-user-images.githubusercontent.com/5087599/384463166-fea5f3cb-f062-4916-9aed-3811ed6ffe96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzE5NDgsIm5iZiI6MTczMTEzMTY0OCwicGF0aCI6Ii81MDg3NTk5LzM4NDQ2MzE2Ni1mZWE1ZjNjYi1mMDYyLTQ5MTYtOWFlZC0zODExZWQ2ZmZlOTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDlUMDU1NDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDc3ZjljYzY4NGMzZjRiZjQwOWUzMjNhMTE3ZDY2ZmQxOWI0MTc1MTA2Y2QwNjdhNGEzZTgzMTc1NTc2NTZlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AGM13y2sPbBzgi1cudI6IkcqPf3PbL5lmDR7xzMUHb4)
> 
> i have changed the base_url,but still have the same problem [vectorizer] vectorizer = kag.common.vectorizer.OpenAIVectorizer model = bge-m3 api_key = EMPTY base_url = http://host.docker.internal:11434/v1 vector_dimensions = 1024

It seems like your embedding model is inaccessible in developer mode, please verify the configuration in the following order:
1、Have you deployed your embedding model with ollama（you can refer to [embedding model with ollama](https://openspg.yuque.com/ndx6g9/wc9oyq/agc1runp50cz3wu8#WCmxL)
2、Is your embedding model accessible by KAG ?(you can refer to [Test embedding generation with bge-m3](you can refer to [embedding model with ollama](https://openspg.yuque.com/ndx6g9/wc9oyq/agc1runp50cz3wu8#WCmxL)

**Comment by xionghuaidong** [comment]
You can try the embedding services provided by SiliconCloud and OpenAI.

* <https://cloud.siliconflow.cn/models>
* <https://platform.openai.com/docs/guides/embeddings>
