### ISSUE TITLE
docker-compose.yml 并用 Docker Compose 启动服务   neo4j安装失败

### ISSUE THREAD

**Issue by zhangqaws** [OpenSPG/KAG#57]
*****************************************************************************
 *********************** Enhanced By DozerDB Plugin ***********************
*****************************************************************************

2024-11-19 10:40:30.081+0000 INFO  This instance is ServerId{b120a046} (b120a046-471b-4b27-9e78-dd359f9ff0ff)
2024-11-19 10:40:31.355+0000 INFO  ======== Neo4j 5.25.1 ========
2024-11-19 10:40:31.456+0000 ERROR Failed to start Neo4j on 0.0.0.0:7474.
java.lang.RuntimeException: Error starting Neo4j database server at /data/databases
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:288) ~[neo4j-5.25.1.jar:5.25.1]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:223) ~[neo4j-5.25.1.jar:5.25.1]
	at org.neo4j.server.DozerDbBootstrapper.createNeo(DozerDbBootstrapper.java:46) ~[dozerdb-core-5.25.1-1.1.0-alpha.1.jar:5.25.1-1.1.0-alpha.1]
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:185) [neo4j-5.25.1.jar:5.25.1-1.1.0-alpha.1]
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:100) [neo4j-5.25.1.jar:5.25.1-1.1.0-alpha.1]
	at org.neo4j.server.DozerDbEntryPoint.main(DozerDbEntryPoint.java:48) [dozerdb-core-5.25.1-1.1.0-alpha.1.jar:5.25.1-1.1.0-alpha.1]
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.GlobalExtensions@6ff37443' failed to initialize. Please see the attached cause exception "org.neo4j.internal.batchimport.Configuration".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:334) ~[neo4j-common-5.25.1.jar:5.25.1]
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.25.1.jar:5.25.1]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.25.1.jar:5.25.1]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:279) ~[neo4j-5.25.1.jar:5.25.1]
	... 5 more
Caused by: org.neo4j.kernel.extension.FailedToBuildExtensionException: Failed to build kernel extension Extension:OpenGraphDataScienceExtension[gds.open] because it is compiled with a reference to a class, method, or field, that is not in the class path: 'org/neo4j/internal/batchimport/Configuration'. The most common cause of this problem, is that Neo4j has been upgraded without also upgrading all installed extensions, such as APOC. Make sure that all of your extensions are build against your specific version of Neo4j.
	at org.neo4j.kernel.extension.ExtensionFailureStrategies.wrap(ExtensionFailureStrategies.java:56) ~[neo4j-kernel-5.25.1.jar:5.25.1]
	at org.neo4j.kernel.extension.ExtensionFailureStrategies$1.handle(ExtensionFailureStrategies.java:68) ~[neo4j-kernel-5.25.1.jar:5.25.1]
	at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:68) ~[neo4j-kernel-5.25.1.jar:5.25.1]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.25.1.jar:5.25.1]
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.25.1.jar:5.25.1]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.25.1.jar:5.25.1]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:279) ~[neo4j-5.25.1.jar:5.25.1]
	... 5 more
Caused by: java.lang.NoClassDefFoundError: org/neo4j/internal/batchimport/Configuration
	at org.neo4j.gds.procedures.integration.LogAccessor.getLog(LogAccessor.java:33) ~[open-gds-2.8.0-alpha01.jar:?]
	at org.neo4j.gds.extension.OpenGraphDataScienceExtension.newInstance(OpenGraphDataScienceExtension.java:52) ~[open-gds-2.8.0-alpha01.jar:?]
	at org.neo4j.gds.extension.OpenGraphDataScienceExtension.newInstance(OpenGraphDataScienceExtension.java:43) ~[open-gds-2.8.0-alpha01.jar:?]
	at org.neo4j.kernel.extension.AbstractExtensions.newInstance(AbstractExtensions.java:124) ~[neo4j-kernel-5.25.1.jar:5.25.1]
	at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:62) ~[neo4j-kernel-5.25.1.jar:5.25.1]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.25.1.jar:5.25.1]
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.25.1.jar:5.25.1]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.25.1.jar:5.25.1]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:279) ~[neo4j-5.25.1.jar:5.25.1]
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.neo4j.internal.batchimport.Configuration
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at org.neo4j.gds.procedures.integration.LogAccessor.getLog(LogAccessor.java:33) ~[open-gds-2.8.0-alpha01.jar:?]
	at org.neo4j.gds.extension.OpenGraphDataScienceExtension.newInstance(OpenGraphDataScienceExtension.java:52) ~[open-gds-2.8.0-alpha01.jar:?]
	at org.neo4j.gds.extension.OpenGraphDataScienceExtension.newInstance(OpenGraphDataScienceExtension.java:43) ~[open-gds-2.8.0-alpha01.jar:?]
	at org.neo4j.kernel.extension.AbstractExtensions.newInstance(AbstractExtensions.java:124) ~[neo4j-kernel-5.25.1.jar:5.25.1]
	at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:62) ~[neo4j-kernel-5.25.1.jar:5.25.1]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.25.1.jar:5.25.1]
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.25.1.jar:5.25.1]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.25.1.jar:5.25.1]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:279) ~[neo4j-5.25.1.jar:5.25.1]
	... 5 more
2024-11-19 10:40:31.462+0000 INFO  Neo4j Server shutdown initiated by request
2024-11-19 10:40:31.462+0000 INFO  Stopped.

**Comment by andylau-55** [comment]
Thank you for your feedback. Please delete the local cache and pull the latest openspg-neo4j image again

**Comment by zhangqaws** [comment]
Thank you，The problem has been resolved @andylau-55
