### ISSUE TITLE
安装openspg-knext出现异常

### ISSUE THREAD

**Issue by Rama-19** [OpenSPG/KAG#72]
Collecting openspg-knext
  Using cached openspg_knext-0.5.20241025.1-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: wget==3.2 in /root/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from openspg-knext) (3.2)
Requirement already satisfied: pytest==7.4.2 in /root/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from openspg-knext) (7.4.2)
Requirement already satisfied: json5 in /root/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from openspg-knext) (0.9.28)
Requirement already satisfied: retrying==1.3.4 in /root/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from openspg-knext) (1.3.4)
Requirement already satisfied: tabulate==0.9.0 in /root/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from openspg-knext) (0.9.0)
Requirement already satisfied: jieba==0.42.1 in /root/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from openspg-knext) (0.42.1)
Requirement already satisfied: nltk==3.8.1 in /root/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from openspg-knext) (3.8.1)
Requirement already satisfied: tqdm==4.66.1 in /root/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from openspg-knext) (4.66.1)
Requirement already satisfied: six==1.16.0 in /root/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from openspg-knext) (1.16.0)
Requirement already satisfied: click==8.1.7 in /root/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from openspg-knext) (8.1.7)
Requirement already satisfied: dateutils==0.6.12 in /root/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from openspg-knext) (0.6.12)
Requirement already satisfied: certifi==2023.11.17 in /root/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from openspg-knext) (2023.11.17)
Collecting urllib3==2.1.0 (from openspg-knext)
  Using cached urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: python-dateutil==2.8.2 in /root/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from openspg-knext) (2.8.2)
Requirement already satisfied: networkx==3.1 in /root/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from openspg-knext) (3.1)
Collecting pydantic==2.5.2 (from openspg-knext)
  Using cached pydantic-2.5.2-py3-none-any.whl.metadata (65 kB)
Requirement already satisfied: requests==2.31.0 in /root/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from openspg-knext) (2.31.0)
Requirement already satisfied: setuptools==60.2.0 in /root/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from openspg-knext) (60.2.0)
Requirement already satisfied: psutil in /root/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from openspg-knext) (6.1.0)
Collecting Jinja2==3.0.3 (from openspg-knext)
  Using cached Jinja2-3.0.3-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: cachetools==5.3.2 in /root/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from openspg-knext) (5.3.2)
Collecting numpy==1.23.1 (from openspg-knext)
  Using cached numpy-1.23.1.tar.gz (10.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/root/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/root/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/.pyenv/versions/3.12.0/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/home/tmp/pip-build-env-tjonj8b_/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/home/tmp/pip-build-env-tjonj8b_/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/home/tmp/pip-build-env-tjonj8b_/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by xionghuaidong** [comment]
Maybe your Python version is too latest and some dependent Python packages are not ported to Python 3.12 yet.
You can try Python 3.10 (maybe installed via Conda or pyenv).
