### ISSUE TITLE
"Failed to invoke proceduer `db.index.fulltext.queryNodes`

### ISSUE THREAD

**Issue by BinLiang2021** [OpenSPG/KAG#75]
run example: 2wiki solver

config change:
```bash
[vectorizer]
vectorizer = kag.common.vectorizer.OpenAIVectorizer
model = text-embedding-3-small	
vector_dimensions = 1536
api_key = {My Key}


[llm]
client_type = vllm
base_url = http://127.0.0.1:8000/v1
model = meta-llama/Meta-Llama-3.1-70B-Instruct
```

I modift the code about vectorizer, llm and make sure that they will work.

But it will 
```bash
HTTP response headers: HTTPHeaderDict({'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'Remote': '172.18.0.4', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Date': 'Wed, 27 Nov 2024 06:12:42 GMT', 'Connection': 'close'})
HTTP response body: "Failed to invoke procedure `db.index.fulltext.queryNodes`: Caused by: java.lang.IllegalArgumentException: There is no such fulltext schema index: _default_text_index"
Traceback (most recent call last):
  File "/data/home/bin_liang/documents/KAG/kag/common/retriever/kag_retriever.py", line 383, in get_all_docs_by_id
    text_matched = self.sc.search_text(query, [self.schema_util.get_label_within_prefix(CHUNK_TYPE)], topk=1)
  File "/data/home/bin_liang/miniconda3/envs/kag-demo/lib/python3.10/site-packages/knext/search/client.py", line 33, in search_text
    records = self._rest_client.search_text_post(text_search_request=req)
  File "/data/home/bin_liang/miniconda3/envs/kag-demo/lib/python3.10/site-packages/knext/search/rest/search_api.py", line 69, in search_text_post
    return self.search_text_post_with_http_info(**kwargs)  # noqa: E501
  File "/data/home/bin_liang/miniconda3/envs/kag-demo/lib/python3.10/site-packages/knext/search/rest/search_api.py", line 145, in search_text_post_with_http_info
    return self.api_client.call_api(
  File "/data/home/bin_liang/miniconda3/envs/kag-demo/lib/python3.10/site-packages/knext/common/rest/api_client.py", line 419, in call_api
    return self.__call_api(
  File "/data/home/bin_liang/miniconda3/envs/kag-demo/lib/python3.10/site-packages/knext/common/rest/api_client.py", line 219, in __call_api
    raise e
  File "/data/home/bin_liang/miniconda3/envs/kag-demo/lib/python3.10/site-packages/knext/common/rest/api_client.py", line 207, in __call_api
    response_data = self.request(
  File "/data/home/bin_liang/miniconda3/envs/kag-demo/lib/python3.10/site-packages/knext/common/rest/api_client.py", line 495, in request
    return self.rest_client.POST(
  File "/data/home/bin_liang/miniconda3/envs/kag-demo/lib/python3.10/site-packages/knext/common/rest/rest.py", line 345, in POST
    return self.request(
  File "/data/home/bin_liang/miniconda3/envs/kag-demo/lib/python3.10/site-packages/knext/common/rest/rest.py", line 257, in request
    raise ApiException(http_resp=r)
knext.common.rest.exceptions.ApiException: (400)
Reason:
HTTP response headers: HTTPHeaderDict({'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'Remote': '172.18.0.4', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Date': 'Wed, 27 Nov 2024 06:12:42 GMT', 'Connection': 'close'})
HTTP response body: "Failed to invoke procedure `db.index.fulltext.queryNodes`: Caused by: java.lang.IllegalArgumentException: There is no such fulltext schema index: _default_text_index"

INFO:httpx:HTTP Request: POST http://127.0.0.1:30102/v1/chat/completions "HTTP/1.1 200 OK"
INFO:__main__:

so the answer for 'Which film was released first, Aas Ka Panchhi or Phoolwari?' is: Aas Ka Panchhi


parallelQaAndEvaluate completing: 100%|███████████████████████| 2/2 [00:31<00:00, 15.59s/it]
```

**Comment by xionghuaidong** [comment]
Did you execute the following command?

```bash
knext schema commit
```

The full-text index is created during the process.

**Comment by BinLiang2021** [comment]
Hi, 
    Thanks for your reply. 
    The first time I met this error, I did not run this command. 
    Then, I run this command but with the same error.

**Comment by xionghuaidong** [comment]
You can visit to <http://127.0.0.1:7474/browser/> (replace ``127.0.0.1`` with the actual IP of the Neo4j container), connect to the Neo4j server, and switch to the Neo4j database for 2wiki.

Then execute the following Cypher statement to make sure the full-text index ``_default_text_index`` is created properly.

```text
SHOW FULLTEXT INDEX;
```

Like this:

![image](https://github.com/user-attachments/assets/8c0a8674-ab0b-41f2-b159-cd8c0fe50517)
