### ISSUE TITLE
KAGExtractor Processing, ollama /api/generate keeps give 200 and 500 alternately

### ISSUE THREAD

**Issue by pecanjk** [OpenSPG/KAG#81]
I'm not sure if the 200/500 comes from the extensive request LLM? if so, can I reduce the request num or wait longer time or modify ollama server model cfg? and how. Thanks

**python builder/indexer.py** terminal give such output
> Processing KAGExtractor:   2%|█▌                                                                                  | 32/1689 [05:26<3:19:20,  7.22s/it]INFO:httpx:HTTP Request: POST http://localhost:11434/api/generate "HTTP/1.1 200 OK"
> Processing KAGExtractor:   2%|█▋                                                                                  | 34/1689 [05:45<3:48:49,  8.30s/it]INFO:httpx:HTTP Request: POST http://localhost:11434/api/generate "HTTP/1.1 200 OK"
> INFO:httpx:HTTP Request: POST http://localhost:11434/api/generate "HTTP/1.1 200 OK"
> INFO:httpx:HTTP Request: POST http://localhost:11434/api/generate "HTTP/1.1 200 OK"
> INFO:httpx:HTTP Request: POST http://localhost:11434/api/generate "HTTP/1.1 500 Internal Server Error"
> INFO:httpx:HTTP Request: POST http://localhost:11434/api/generate "HTTP/1.1 500 Internal Server Error"
> INFO:httpx:HTTP Request: POST http://localhost:11434/api/generate "HTTP/1.1 500 Internal Server Error"

**ollma server terminal gives such output**

>  time=2024-11-28T10:51:00.406+08:00 level=WARN source=sched.go:646 msg="gpu VRAM usage didn't recover within timeout" seconds=5.765904174 model=/home/wangtao/.ollama/models/blobs/sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe
> time=2024-11-28T10:51:01.482+08:00 level=WARN source=sched.go:646 msg="gpu VRAM usage didn't recover within timeout" seconds=6.841584149 model=/home/wangtao/.ollama/models/blobs/sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe
> time=2024-11-28T10:51:02.489+08:00 level=WARN source=sched.go:646 msg="gpu VRAM usage didn't recover within timeout" seconds=7.848922066 model=/home/wangtao/.ollama/models/blobs/sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe
> time=2024-11-28T10:51:03.509+08:00 level=INFO source=sched.go:714 msg="new model will fit in available VRAM in single GPU, loading" model=/home/wangtao/.ollama/models/blobs/sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe gpu=GPU-31101936-17af-d730-8d61-2e7da66873cf parallel=4 available=25158156288 required="6.2 GiB"

**Comment by pecanjk** [comment]
> I'm not sure if the 200/500 comes from the extensive request LLM? if so, can I reduce the request num or wait longer time or modify ollama server model cfg? and how. Thanks
> 
> **python builder/indexer.py** terminal give such output
> 
> > Processing KAGExtractor:   2%|█▌                                                                                  | 32/1689 [05:26<3:19:20,  7.22s/it]INFO:httpx:HTTP Request: POST http://localhost:11434/api/generate "HTTP/1.1 200 OK"
> > Processing KAGExtractor:   2%|█▋                                                                                  | 34/1689 [05:45<3:48:49,  8.30s/it]INFO:httpx:HTTP Request: POST http://localhost:11434/api/generate "HTTP/1.1 200 OK"
> > INFO:httpx:HTTP Request: POST http://localhost:11434/api/generate "HTTP/1.1 200 OK"
> > INFO:httpx:HTTP Request: POST http://localhost:11434/api/generate "HTTP/1.1 200 OK"
> > INFO:httpx:HTTP Request: POST http://localhost:11434/api/generate "HTTP/1.1 500 Internal Server Error"
> > INFO:httpx:HTTP Request: POST http://localhost:11434/api/generate "HTTP/1.1 500 Internal Server Error"
> > INFO:httpx:HTTP Request: POST http://localhost:11434/api/generate "HTTP/1.1 500 Internal Server Error"
> 
> **ollma server terminal gives such output**
> 
> > time=2024-11-28T10:51:00.406+08:00 level=WARN source=sched.go:646 msg="gpu VRAM usage didn't recover within timeout" seconds=5.765904174 model=/home/xxx/.ollama/models/blobs/sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe
> > time=2024-11-28T10:51:01.482+08:00 level=WARN source=sched.go:646 msg="gpu VRAM usage didn't recover within timeout" seconds=6.841584149 model=/home/xxx/.ollama/models/blobs/sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe
> > time=2024-11-28T10:51:02.489+08:00 level=WARN source=sched.go:646 msg="gpu VRAM usage didn't recover within timeout" seconds=7.848922066 model=/home/xxx/.ollama/models/blobs/sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe
> > time=2024-11-28T10:51:03.509+08:00 level=INFO source=sched.go:714 msg="new model will fit in available VRAM in single GPU, loading" model=/home/xxx/.ollama/models/blobs/sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe gpu=GPU-31101936-17af-d730-8d61-2e7da66873cf parallel=4 available=25158156288 required="6.2 GiB"

ollama terminal also output such log.
[GIN] 2024/11/28 - 10:58:45 | 200 | 40.338236468s |       127.0.0.1 | POST     "/api/generate"
panic: failed to decode batch: could not find a kv cache slot

goroutine 7 [running]:
main.(*Server).run(0xc0001d2120, {0x556397570d60, 0xc0001ac0a0})
        github.com/ollama/ollama/llama/runner/runner.go:336 +0x23e
created by main.main in goroutine 1
        github.com/ollama/ollama/llama/runner/runner.go:955 +0xc52
[GIN] 2024/11/28 - 10:58:45 | 500 | 40.471320211s |       127.0.0.1 | POST     "/api/generate"

**Comment by caszkgui** [comment]
> builder/indexer.py

Number of concurrency task can by modified by adjusting max_workers of BuilderChain, you can refer to [buildKB method of hotpotqa indexer](https://github.com/OpenSPG/KAG/blob/master/kag/examples/hotpotqa/builder/indexer.py)

![image](https://github.com/user-attachments/assets/d2c53373-3187-45a0-8d8e-0d3a7db6d17f)
