### ISSUE TITLE
where is the component'rest'?

### ISSUE THREAD

**Issue by stoveZhu** [OpenSPG/KAG#91]
i'm learning how to use the kag with the example 'medicine'. i tried to run the` evaForMedicine.py` but got error below

```
Traceback (most recent call last):
  File "d:\work_projects\kag\KAG-master\kag\examples\medicine\solver\evaForMedicine.py", line 5, in <module>
    from kag.solver.logic.solver_pipeline import SolverPipeline
  File "d:\work_projects\kag\kag-master\kag\solver\logic\solver_pipeline.py", line 4, in <module>
    from kag.interface.solver.kag_reasoner_abc import KagReasonerABC
  File "d:\work_projects\kag\kag-master\kag\interface\solver\kag_reasoner_abc.py", line 6, in <module>
    from kag.solver.logic.core_modules.lf_solver import LFSolver
  File "d:\work_projects\kag\kag-master\kag\solver\logic\core_modules\lf_solver.py", line 15, in <module>
    from kag.solver.logic.core_modules.lf_executor import LogicExecutor
  File "d:\work_projects\kag\kag-master\kag\solver\logic\core_modules\lf_executor.py", line 6, in <module>
    from kag.common.graphstore.graph_store import GraphStore
  File "d:\work_projects\kag\kag-master\kag\common\graphstore\__init__.py", line 30, in <module>
    from kag.common.graphstore.rest.graph_api import GraphApi
  File "d:\work_projects\kag\kag-master\kag\common\graphstore\rest\__init__.py", line 30, in <module>
    from kag.common.graphstore.rest.graph_api import GraphApi
  File "d:\work_projects\kag\kag-master\kag\common\graphstore\rest\graph_api.py", line 20, in <module>
    from kag.common.rest.api_client import ApiClient
ModuleNotFoundError: No module named 'kag.common.rest'
```

is that `kag.common.rest`has been deleted some versions ago?

**Comment by thundax-lyp** [comment]
in file https://github.com/OpenSPG/KAG/blob/bf1874491090df334b58b407026dc903853c4bb8/kag/examples/2wiki/solver/evaFor2wiki.py

```python
def qa(self, query):
        # CA
        resp = SolverPipeline()
        answer, traceLog = resp.run(query)

        logger.info(f"\n\nso the answer for '{query}' is: {answer}\n\n")
        return answer, traceLog
```

you can also define your own SolverPipeline

**Comment by caszkgui** [comment]
> i'm learning how to use the kag with the example 'medicine'. i tried to run the` evaForMedicine.py` but got error below
> 
> ```
> Traceback (most recent call last):
>   File "d:\work_projects\kag\KAG-master\kag\examples\medicine\solver\evaForMedicine.py", line 5, in <module>
>     from kag.solver.logic.solver_pipeline import SolverPipeline
>   File "d:\work_projects\kag\kag-master\kag\solver\logic\solver_pipeline.py", line 4, in <module>
>     from kag.interface.solver.kag_reasoner_abc import KagReasonerABC
>   File "d:\work_projects\kag\kag-master\kag\interface\solver\kag_reasoner_abc.py", line 6, in <module>
>     from kag.solver.logic.core_modules.lf_solver import LFSolver
>   File "d:\work_projects\kag\kag-master\kag\solver\logic\core_modules\lf_solver.py", line 15, in <module>
>     from kag.solver.logic.core_modules.lf_executor import LogicExecutor
>   File "d:\work_projects\kag\kag-master\kag\solver\logic\core_modules\lf_executor.py", line 6, in <module>
>     from kag.common.graphstore.graph_store import GraphStore
>   File "d:\work_projects\kag\kag-master\kag\common\graphstore\__init__.py", line 30, in <module>
>     from kag.common.graphstore.rest.graph_api import GraphApi
>   File "d:\work_projects\kag\kag-master\kag\common\graphstore\rest\__init__.py", line 30, in <module>
>     from kag.common.graphstore.rest.graph_api import GraphApi
>   File "d:\work_projects\kag\kag-master\kag\common\graphstore\rest\graph_api.py", line 20, in <module>
>     from kag.common.rest.api_client import ApiClient
> ModuleNotFoundError: No module named 'kag.common.rest'
> ```
> 
> is that `kag.common.rest`has been deleted some versions ago?

You can refer to [User Guide for Quick Start](https://openspg.yuque.com/ndx6g9/docs_en/rs7gr8g4s538b1n7) to get detail information on start up, and we all provide [reproduce steps for medicine](https://openspg.yuque.com/ndx6g9/docs_en/bkvfaunnpl65rsrk)
